language: c
compiler:
  - gcc

addons:
  apt:
    packages:
      - gcc-avr
      - binutils-avr
      - avr-libc

before_script:
  - mkdir build
  - mkdir -p test/support

install:
  - gem install ceedling

script: ceedling test:all
